name: lando-cron
services:
  worker:
    type: compose
    build_as_root:
      - "mkdir -p /var/log/cron"
      - "touch /var/log/cron/timestamp.log"
      - "chmod -R a+rw /var/log/cron"
    services:
      image: devwithlando/php:7.2-fpm
      command: docker-php-entrypoint /usr/local/bin/php /app/runner.php >out 2>&1